//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeSharp.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeeSharp.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement &apos;{0}&apos; must be used inside a using block statement in the form &apos;using(var x = {0}) {{ x.InvokeMember(); }}&apos; to ensure finalizer code runs..
        /// </summary>
        internal static string BS3001Message1A {
            get {
                return ResourceManager.GetString("BS3001Message1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation has to be inside block using statement.
        /// </summary>
        internal static string BS3001Title {
            get {
                return ResourceManager.GetString("BS3001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement &apos;{0}&apos; must be used inside a using statement to ensure final code runs..
        /// </summary>
        internal static string BS3002Message1A {
            get {
                return ResourceManager.GetString("BS3002Message1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invcoation has to be inside using statement.
        /// </summary>
        internal static string BS3002Title {
            get {
                return ResourceManager.GetString("BS3002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; default constructs object of type &apos;{1}&apos; which is marked as a non default constructable type. Please use a parameterized constructor instead..
        /// </summary>
        internal static string BS3003Message2A {
            get {
                return ResourceManager.GetString("BS3003Message2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default constructor usage not allowed.
        /// </summary>
        internal static string BS3003Title {
            get {
                return ResourceManager.GetString("BS3003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; may return a default constructed object of type  &apos;{1}&apos; which is marked as a non default constructable type. Please use a method variant that does not return default constructed instances. E.g. use &apos;Single()&apos; instead of &apos;SingleOrDefault()&apos;..
        /// </summary>
        internal static string BS3004Message2A {
            get {
                return ResourceManager.GetString("BS3004Message2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default constructed type may be returned.
        /// </summary>
        internal static string BS3004Title {
            get {
                return ResourceManager.GetString("BS3004Title", resourceCulture);
            }
        }
    }
}
